name: ci

on:
  push:
    branches: ["**"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        run: go tool staticcheck ./...

      - name: Test
        run: go test -race -shuffle=on ./...
